export interface StudentResponse {
    id_persona: string,
    dni: string,
    nombres: string,
    apePaterno: string,
    apeMaterno: string,
    nacimiento: string,
    direccion: string,
    referencia: string
    genero: string,
    estado: string,
    fecha_registro: string,
    id_usuario: string,
    nickname: string,
    password: string,
    role: string,
    id_matricula: string,
    fecha: string,
    pago: string,
    monto: number,
    id_estudiante: string,
    id_año: string,
    nombre: string,
    numero: string,
    seccion: string,
    turno: string,
    id_anio?: string
}